name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full history is fetched to access tags

      - name: Set up Git
        run: git fetch --tags

      - name: Get the latest tag and increment version
        id: version
        run: |
          # Get the latest tag (if any)
          latest_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")

          # Increment the version
          version_number=$(echo $latest_tag | sed 's/^v//')
          new_version=$(echo $version_number | awk -F. -v OFS=. '{$NF++;print}')

          # Output the new version for debugging
          echo "New version will be $new_version"
          echo "VERSION=$new_version" >> $GITHUB_ENV
          
      - name: Verify version variable
        run: echo "VERSION=${{ env.VERSION }}"

      - name: Create a new version tag
        run: |
          git tag ${{ env.VERSION }}
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${{ env.VERSION }}

  docker:
    runs-on: ubuntu-latest
    needs: version
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/jellyfin-symlink-helper:latest
            ${{ secrets.DOCKER_USERNAME }}/jellyfin-symlink-helper:${{ env.VERSION }}
